databases:
  - name: mbdb
    plan: free
    databaseName: mbdb
    user: mbdb

services:
  - type: web
    plan: free
    name: bookstore
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_project.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mbdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4